# Generated by Django 3.2.3 on 2021-05-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва акції')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=500, verbose_name='Опис')),
                ('end', models.CharField(max_length=100, verbose_name='Кінець акції')),
                ('image', models.ImageField(upload_to='', verbose_name='Обрати фото')),
            ],
            options={
                'verbose_name': 'Акція',
                'verbose_name_plural': 'Акції',
            },
        ),
    ]
