# Generated by Django 3.2.3 on 2021-06-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_alter_promotions_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotions',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='end',
            field=models.CharField(blank=True, max_length=100, verbose_name='Кінець акції'),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Обрати фото'),
        ),
    ]
