# Generated by Django 3.2.3 on 2021-05-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('number_tel', models.IntegerField(verbose_name='Номер телефону')),
                ('email', models.EmailField(max_length=254, verbose_name='Пошта')),
                ('instagram', models.CharField(max_length=30)),
                ('telegram', models.CharField(max_length=15)),
                ('schedule', models.TextField(verbose_name='Графік роботи')),
            ],
            options={
                'verbose_name': 'Котактні дані',
                'verbose_name_plural': 'Котактні дані',
            },
        ),
    ]
