# Generated by Django 3.2.3 on 2021-06-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210601_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_tel',
            field=models.CharField(default=1, max_length=12, verbose_name='Мобільний номер'),
            preserve_default=False,
        ),
    ]
