# Generated by Django 3.2.3 on 2021-06-03 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_number_tel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Користувач', 'verbose_name_plural': 'Користувачі'},
        ),
    ]
