# Generated by Django 3.2.3 on 2021-06-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kind',
            options={'verbose_name': 'Каталог продукту', 'verbose_name_plural': 'Каталоги продуктів'},
        ),
        migrations.AlterField(
            model_name='kind',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='kind',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Назва'),
        ),
    ]
