# Generated by Django 3.2.3 on 2021-06-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.AddField(
            model_name='order',
            name='number_tel',
            field=models.CharField(blank=True, max_length=12, verbose_name='Номер телефону'),
        ),
    ]
